### ISSUE TITLE
User address

### ISSUE THREAD

**Issue by projenix** [ConjurTech/switcheo-api-examples#1]
Hello,

what do you mean by user address in user.js? public neo address? that's not 40 characters long.

Can you please advise?

Thanks,

**Comment by projenix** [comment]
Got it, address is script hash of the contract, can get it from here:
https://api.switcheo.network/v2/exchange/contracts

I will just leave this update here.

Thanks,

**Comment by projenix** [comment]
No I don't think it's that, can you please help?

Thank you,

**Comment by RavenXce** [comment]
That is the script hash of the user's public key, which is 20 bytes / 40 hex characters long. It can be converted into the Base58 address which starts with `A`.

Please see this documentation for more details on how to do so: https://docs.switcheo.network/#addresses
